### ISSUE TITLE
Experiencing a reproducible error

### ISSUE THREAD

**Issue by adamrossnelson** [bbradfield/brad-stata#1]
Here is code that reproduces the error I’m experiencing. It is random data modeled after another project I’m working on with proprietary data.
```
use https://raw.githubusercontent.com/adamrossnelson/HelloWorld/master/b_test.dta
sum
bradbook
```
According to the summarize command the variable `unitid` has a min of 69 and a max of 486854, mean of 185679, etc. The `isYr` has a min of 0, and max of 2015 with a mean of 2015. Also, `refweap` has its own set of values.
However bradbook is displaying the same set of summary statistics for each variable. To troubleshoot I uninstalled and then reinstalled `bradbook` using (no change):
```
net install bradsuite, from(https://raw.githubusercontent.com/bbradfield/brad-stata/master)
```

I did discover that after running `compress` the error no longer occurs. Update: `compress` isn't a complete fix. Note that after running compress, the summary stats for `unitid` appear to be correct, the summary stats for `isYr` are correct, but the summary stats for `refweap` are incorrect.

**Comment by bbradfield** [comment]
Hi Adam,

Good find. I think what is happening is that a captured error is preventing an update to the summary statistics. I will hopefully updated bradbook later this week to fix that (it should be fairly simple). I'll mark this when I am done.

Thanks for the feedback!

**Comment by bbradfield** [comment]
@adamrossnelson Should be good to go now, tested on that dataset. Closing this issue for now.

**Comment by adamrossnelson** [comment]
Also confirmed to work on proprietary data. Thanks again for a great package.
